# _config.yml
title: Chang Cheng

# Social links (used for tiny icons in the top navigation)
email: cheng12@stanford.edu
github_url: https://github.com/dcheng728
inspire_url: https://inspirehep.net/authors/3093156?ui-citation-summary=true

nav:
  - title: "Home"
    url: "/"
  - title: "Physics Self-Study"
    url: "/physics/" 
  - title: "Quiz"
    url: "https://dcheng728.github.io/quiz/"
